import {BoardState} from '../core/boardState.js?v=2026-09-13.2';
import {applyMove,isValidMove,getGroup} from '../core/ruleEngine.js?v=2026-09-13.2';
export const CONNECTION_SHAPES=[
{name:'Kosumi',tr:'Çapraz adım',jp:'コスミ',kr:'마늘모 · maneul-mo',cn:'尖 · jiān',geometry:'Bir yatay + bir dikey: çapraz komşu.',purpose:'Yakındaki taşla yakın ilişkiyi koruyarak çapraz yönde gelişir. Sıçrama kadar uzak gitmez.',warning:'Çapraz taşlar henüz aynı zincir değildir. İki ortak bağlantı noktası boşken birine gelen rakibe ötekinden bağlanılabilir. Nefes darlığı ve çevredeki rakip taşlar bu ilişkiyi değiştirebilir.',stones:[[2,3],[3,2]],root:[3,2],markers:[[2,2,'A'],[3,3,'B']],branches:[{label:'Beyaz A’ya gelsin',opp:[2,2],answer:[3,3]},{label:'Beyaz B’ye gelsin',opp:[3,3],answer:[2,2]}]},
{name:'One-space jump',tr:'Bir aralık sıçrama · ikken tobi',jp:'一間トビ',kr:'한칸 · han-kan',cn:'跳 · tiào',geometry:'Aynı doğrultuda iki çizgi ilerle; arada bir boş kesişim bırak.',purpose:'Merkeze çıkmak ve daha hızlı gelişmek için kullanılır. Boş aralık sayesinde taşlar daha geniş yer tutar.',warning:'Aradaki A noktası bir zayıflıktır. Rakip burada oynarsa iki taş fiziksel olarak birleşmez. Destek taşları, nefesler ve devam hamleleri bağlantının korunup korunamayacağını belirler.',stones:[[2,3],[2,1]],root:[2,1],markers:[[2,2,'A']],probe:[2,2]},
{name:'Keima',tr:'At adımı',jp:'ケイマ',kr:'날일자 · nal-il-ja',cn:'小飞 · xiǎo fēi',geometry:'Bir yönde iki, öteki yönde bir çizgi: 2 × 1 ilişkisi.',purpose:'Çapraz yönde hızlı gelişmek, köşeyi desteklemek veya rakibi çevrelemek için kullanılır. Bir aralık sıçramadan farklı bir geometridir.',warning:'Keima sıkı bağlantı değildir. Rakip araya temas edip kesme yolları arayabilir. A yalnızca bir temas örneği: başarılı kesme kararı çevre taşlarına ve kimi konumlarda merdivene bağlıdır.',stones:[[2,3],[4,2]],root:[4,2],markers:[[3,2,'A']],probe:[3,2]},
{name:'Bambu',tr:'Bambu bağlantısı · takefu',jp:'タケフ · 竹節',kr:'쌍립 · ssangnip',cn:'竹节 · zhú jié',geometry:'İki paralel ikili taş; aralarında bir boş çizgi ve iki geçit.',purpose:'İki bağlantı yolu sağlar. Rakip bir geçidi tutarsa ötekinden sağlam bağlantıya dönüştürülür.',warning:'Şemada iki ayrı zincir vardır. Beyaz A veya B’ye girince siyah öteki noktada oynayıp bütün taşları tek zincir yapar. Burada cevap hamlesi gösteriliyor; her çevre koşulunda otomatik güvenlik varsayılmıyor.',stones:[[2,2],[3,2],[2,4],[3,4]],root:[3,2],markers:[[2,3,'A'],[3,3,'B']],branches:[{label:'Beyaz A’dan girsin',opp:[2,3],answer:[3,3]},{label:'Beyaz B’den girsin',opp:[3,3],answer:[2,3]}]}
];
export function orientedShape(index,direction=0){const s=CONNECTION_SHAPES[index];function tr(p){let [x,y]=p;if(direction>=4)x=5-x;for(let i=0;i<direction%4;i++)[x,y]=[5-y,x];return [x,y,...p.slice(2)]}return {...s,stones:s.stones.map(tr),root:tr(s.root),markers:s.markers.map(tr)}}
export function buildConnectionBoard(s,omit=false){let b=new BoardState(19);for(const p of s.stones){if(omit&&p[0]===s.root[0]&&p[1]===s.root[1])continue;b=applyMove(b,p[0]+6,p[1]+6,'black').newState}return b}
export function validShapeCompletion(s,index,x,y){const a=s.stones.find(p=>p[0]!==s.root[0]||p[1]!==s.root[1]),dx=Math.abs(x-a[0]),dy=Math.abs(y-a[1]);return index===0?dx===1&&dy===1:index===1?(dx===2&&dy===0)||(dx===0&&dy===2):index===2?(dx===2&&dy===1)||(dx===1&&dy===2):x===s.root[0]&&y===s.root[1]}
export function completedShape(s,index,x,y){const a=s.stones.filter(p=>p[0]!==s.root[0]||p[1]!==s.root[1]);return {...s,stones:[...a,[x,y]],root:[x,y],markers:index===0?[[a[0][0],y,'A'],[x,a[0][1],'B']]:index===1?[[(a[0][0]+x)/2,(a[0][1]+y)/2,'A']]:index===2?[]:s.markers}}
export function connectionStatus(b,s){if(s.stones.some(p=>b.colorAt(p[0]+6,p[1]+6)!=='black'))return {joined:false,canJoin:false,feedback:'Başlangıçtaki siyah taşlardan biri alındı. Yeni denemeyle biçime dön.'};function joined(b){const g=getGroup(b,s.stones[0][0]+6,s.stones[0][1]+6);return s.stones.every(p=>b.colorAt(p[0]+6,p[1]+6)==='black'&&g.has((p[0]+6)+','+(p[1]+6)))}if(joined(b))return {joined:true,canJoin:true,feedback:'Siyah taşlar tek zincir; bu kesme girişimi engellendi.'};let canJoin=false;for(let y=0;y<19&&!canJoin;y++)for(let x=0;x<19&&!canJoin;x++)if(isValidMove(b,x,y,'black').valid)canJoin=joined(applyMove(b,x,y,'black').newState);return {joined:false,canJoin,feedback:canJoin?'Siyah ayrı zincirlerde, fakat tek hamlede bağlanma yolu var.':'Siyah bu konumda bütün parçalarını tek hamlede birleştiremiyor. Kalıcı kesilme veya ölüm kararı için devamı okunmalı.'}}
