import {BoardState} from '../core/boardState.js?v=2026-09-13.5';
import {applyMove,isValidMove,getGroup} from '../core/ruleEngine.js?v=2026-09-13.5';
export const CONNECTION_BOARD_SIZE=9;
export const CONNECTION_OFFSET=1;
export const CONNECTION_SHAPES=[
{name:'Kosumi',tr:'Çapraz adım',jp:'コスミ',kr:'마늘모 · maneul-mo',cn:'尖 · jiān',geometry:'Kosumi, bir taşın çapraz komşusuna oynanan hamledir.',purpose:'Taşlar birbirine yakın kalırken çapraz yönde gelişir.',warning:'Çapraz duran taşlar ayrı zincirlerdir. Beyaz iki ortak bağlantı noktasından birine oynarsa siyah diğerinden bağlanabilir. Çevredeki taşlara ve nefeslere dikkat et.',stones:[[2,3],[3,2]],root:[3,2],markers:[[2,2,'A'],[3,3,'B']],branches:[{label:'Beyaz A’ya gelsin',opp:[2,2],answer:[3,3]},{label:'Beyaz B’ye gelsin',opp:[3,3],answer:[2,2]}]},
{name:'One-space jump',tr:'Bir aralık sıçrama · ikken tobi',jp:'一間トビ',kr:'한칸 · han-kan',cn:'跳 · tiào',geometry:'Bir aralık sıçramada iki taş aynı yatay veya dikey çizgidedir; aralarında bir boş kesişim bulunur.',purpose:'Japonca ikken tobi, İngilizce one-space jump adıyla da anılır. Taşları yakın tutarak daha hızlı gelişmeyi sağlar.',warning:'Aradaki boş nokta kesme girişiminin başlangıcı olabilir. Beyaz burada oynadığında siyahın bağlantıyı nasıl koruyabileceğini dene. Sonuç çevredeki destek taşlarına ve devam hamlelerine bağlıdır.',stones:[[2,3],[2,1]],root:[2,1],markers:[[2,2,'A']],probe:[2,2]},
{name:'Keima',tr:'At adımı',jp:'ケイマ',kr:'날일자 · nal-il-ja',cn:'小飞 · xiǎo fēi',geometry:'Keima, at adımıdır: bir yönde iki, ona dik yönde bir kesişim ilerlenir.',purpose:'Çapraz yönde gelişmek ve köşeyi desteklemek için kullanılır. Kosumiden daha geniş bir adım atar.',warning:'Keima taşları doğrudan bağlamaz. Beyazla araya girip kesme yollarını ara; ardından siyahla karşılık ver. Kesmenin işe yarayıp yaramadığı çevredeki taşlara ve bazen merdivene bağlıdır.',stones:[[2,3],[4,2]],root:[4,2],markers:[[3,2,'A']],probe:[3,2]},
{name:'Bambu',tr:'Bambu bağlantısı · takefu',jp:'タケフ · 竹節',kr:'쌍립 · ssangnip',cn:'竹节 · zhú jié',geometry:'Bambu bağlantısında iki paralel taş çifti arasında bir boş sıra bulunur. Bu boşlukta iki bağlantı noktası vardır.',purpose:'Japonca takefu adıyla da anılır. İki bağlantı noktasından biri kapansa bile diğeri kullanılabilir.',warning:'Beyaz iki boş bağlantı noktasından birine girerse siyah diğerini doldurarak taşlarını birleştirir. Her iki girişi de dene; cevaptan sonra siyah taşların tek zincir olduğunu gözlemle.',stones:[[2,2],[3,2],[2,4],[3,4]],root:[3,2],markers:[[2,3,'A'],[3,3,'B']],branches:[{label:'Beyaz A’dan girsin',opp:[2,3],answer:[3,3]},{label:'Beyaz B’den girsin',opp:[3,3],answer:[2,3]}]}
];
export function orientedShape(index,direction=0){const s=CONNECTION_SHAPES[index];function tr(p){let [x,y]=p;if(direction>=4)x=5-x;for(let i=0;i<direction%4;i++)[x,y]=[5-y,x];return [x,y,...p.slice(2)]}return {...s,stones:s.stones.map(tr),root:tr(s.root),markers:s.markers.map(tr)}}
export function buildConnectionBoard(s,omit=false){let b=new BoardState(CONNECTION_BOARD_SIZE);for(const [i,p] of s.stones.entries()){if(omit&&(s.name==='Bambu'?i!==0:p[0]===s.root[0]&&p[1]===s.root[1]))continue;b=applyMove(b,p[0]+CONNECTION_OFFSET,p[1]+CONNECTION_OFFSET,'black').newState}return b}
// Keep every still-possible bamboo orientation; placement, not a direction menu, chooses it.
export function bambooPlacement(s,placed,x,y){
 if(placed.some(p=>p[0]===x&&p[1]===y))return null;
 const points=[...placed,[x,y]],a=placed[0];
 for(const [w,h] of [[1,2],[2,1]])for(const dx of [0,w])for(const dy of [0,h]){
  const left=a[0]-dx,top=a[1]-dy,corners=[[left,top],[left+w,top],[left,top+h],[left+w,top+h]];
  if(corners.some(p=>p.some(v=>v+CONNECTION_OFFSET<0||v+CONNECTION_OFFSET>=CONNECTION_BOARD_SIZE)))continue;
  if(!points.every(p=>corners.some(q=>q[0]===p[0]&&q[1]===p[1])))continue;
  const markers=w===1?[[left,top+1,'A'],[left+1,top+1,'B']]:[[left+1,top,'A'],[left+1,top+1,'B']];
  return {...s,stones:points,root:[x,y],markers,complete:points.length===4};
 }
 return null;
}
export function validShapeCompletion(s,index,x,y){const a=s.stones.find(p=>p[0]!==s.root[0]||p[1]!==s.root[1]),dx=Math.abs(x-a[0]),dy=Math.abs(y-a[1]);return index===0?dx===1&&dy===1:index===1?(dx===2&&dy===0)||(dx===0&&dy===2):index===2?(dx===2&&dy===1)||(dx===1&&dy===2):x===s.root[0]&&y===s.root[1]}
export function completedShape(s,index,x,y){const a=s.stones.filter(p=>p[0]!==s.root[0]||p[1]!==s.root[1]);return {...s,stones:[...a,[x,y]],root:[x,y],markers:index===0?[[a[0][0],y,'A'],[x,a[0][1],'B']]:index===1?[[(a[0][0]+x)/2,(a[0][1]+y)/2,'A']]:index===2?[]:s.markers}}
export function connectionStatus(b,s){if(s.stones.some(p=>b.colorAt(p[0]+CONNECTION_OFFSET,p[1]+CONNECTION_OFFSET)!=='black'))return {joined:false,canJoin:false,feedback:'Başlangıçtaki siyah taşlardan biri alındı. Yeni denemeyle biçime dön.'};function joined(b){const g=getGroup(b,s.stones[0][0]+CONNECTION_OFFSET,s.stones[0][1]+CONNECTION_OFFSET);return s.stones.every(p=>b.colorAt(p[0]+CONNECTION_OFFSET,p[1]+CONNECTION_OFFSET)==='black'&&g.has((p[0]+CONNECTION_OFFSET)+','+(p[1]+CONNECTION_OFFSET)))}if(joined(b))return {joined:true,canJoin:true,feedback:'Siyah taşlar tek zincir; bu kesme girişimi engellendi.'};let canJoin=false;for(let y=0;y<b.size&&!canJoin;y++)for(let x=0;x<b.size&&!canJoin;x++)if(isValidMove(b,x,y,'black').valid)canJoin=joined(applyMove(b,x,y,'black').newState);return {joined:false,canJoin,feedback:canJoin?'Siyah ayrı zincirlerde, fakat tek hamlede bağlanma yolu var.':'Siyah bu konumda bütün parçalarını tek hamlede birleştiremiyor. Kalıcı kesilme veya ölüm kararı için devamı okunmalı.'}}
