import {orientedShape,buildConnectionBoard,validShapeCompletion,completedShape,connectionStatus} from './connectionShapesPolicy.js?v=2026-09-13.2';
import {applyMove,isValidMove} from '../core/ruleEngine.js?v=2026-09-13.2';
import {mountTopicEndControls} from './topicEndControls.js?v=2026-09-13.2';
let active=null;
export const scene12Connections={
id:'scene-12-connections',version:1,title:'Kesme ve Bağlama',curriculumRef:{lessonId:'l8',concept:'connection'},
mount(context){
 const state=active={step:0,direction:0,built:null,done:new Set(),alive:true,off:null,hover:null,end:null,cutTried:false};context.container.classList.add('s12-scene-host');const root=document.createElement('div');root.className='ls-strip-root s12-root';root.innerHTML='<div class="s12-heading"></div><p class="ls-strip-text s12-body"></p><div class="s12-directions"></div><div class="s12-actions"><button class="ls-strip-btn s12-confirm">Anladım</button><button class="ls-strip-btn s12-reset">Yeni deneme</button><button class="ls-strip-btn s12-next" disabled>Devam</button></div><p class="s05-feedback s12-feedback" role="status"></p>';context.container.append(root);state.root=root;const el=c=>root.querySelector('.s12-'+c),board=context.boardAdapter;
 function shape(){return state.built||orientedShape(Math.floor(state.step/3),state.direction)}
 function visuals(){board.clearMovePreview();board.clearLiberties();board.clearIllegalHints();board.clearRegionMarks()}
 function syncBoard(){board.setSize(19);board.reset();visuals();for(const p of state.board.stones){const a=board.playMove({row:p.y,col:p.x,color:p.color});if(!a.ok)throw new Error('CONNECTION_SEED_MISMATCH')}board.focusPoints([...state.shape.stones.map(p=>({col:p[0]+6,row:p[1]+6})),{col:6,row:6},{col:11,row:11}],{presetName:'center',minZoom:160});if(state.step%3===2)board.showLiberties(state.shape.markers.map(p=>({col:p[0]+6,row:p[1]+6})))}
 function finishStep(){state.done.add(state.step);el('next').disabled=false;if(state.done.size===12)context.emit('scene_completion_unlocked',{})}
 function render(){state.off?.();state.hover?.();state.shape=shape();state.board=buildConnectionBoard(state.shape,state.step%3===1);state.turn=state.step%3===2?'white':'black';state.cutTried=false;state.ply=0;syncBoard();const phase=state.step%3,s=state.shape;root.dataset.stepIndex=state.step;root.dataset.phase=phase;el('heading').textContent=(state.step+1)+' / 12 · '+s.name+' · '+['Tanı','Her yönde kur','Bağlantıyı sorgula'][phase];el('body').textContent=phase===0?s.geometry+' '+s.purpose:phase===1?s.geometry+' Siyah olarak biçimi istediğin uygun yönde tamamla.':s.warning+' Önce beyazla kesmeyi, sonra siyahla savunmayı dene. İstediğin yasal noktalarda devam edebilirsin.';el('confirm').hidden=phase!==0;el('reset').hidden=phase===0;el('next').disabled=!state.done.has(state.step);el('feedback').textContent=phase===2?'Beyaz oynuyorsun. Bağlantı aralığını veya taşların yanını dene.':phase===1?'Siyah oynuyorsun. Kosumi ve sıçrama dört, keima sekiz yönde kurulabilir.':'';el('directions').innerHTML=phase===1?'<label>Şema yönü <select class="s12-direction" aria-label="Şema yönü">'+['0°','90°','180°','270°','Ayna 0°','Ayna 90°','Ayna 180°','Ayna 270°'].map((v,i)=>'<option value="'+i+'" '+(state.direction===i?'selected':'')+'>'+v+'</option>').join('')+'</select></label>':'';const direction=el('direction');if(direction)direction.onchange=()=>{state.direction=+direction.value;state.built=null;render()};board.setInputEnabled(phase!==0);state.off=board.onIntersectionTap(tap);state.hover=board.onIntersectionHover(hit=>{if(!hit||state.step%3===0||(state.step%3===1&&state.done.has(state.step))||!isValidMove(state.board,hit.col,hit.row,state.turn).valid)board.clearMovePreview();else board.setMovePreview({...hit,color:state.turn})});context.emit('scene_assessment_presented',{assessmentIndex:state.step,assessmentCount:12,concept:'connection',assessmentType:phase===0?'confirmation':'board_tap'})}
 function tap(hit){if(!state.alive||state.step%3===0||(state.step%3===1&&state.done.has(state.step)))return;const i=Math.floor(state.step/3),x=hit.col-6,y=hit.row-6,phase=state.step%3;if(phase===1&&!validShapeCompletion(state.shape,i,x,y)){el('feedback').textContent='Bu nokta biçimi tamamlamıyor. Yatay ve dikey uzaklıkları yeniden say.';return}const legal=isValidMove(state.board,hit.col,hit.row,state.turn);if(!legal.valid){el('feedback').textContent='Burada yasal hamle yok; başka boş nokta dene.';return}if(phase===2&&state.turn==='white'){const touched=state.shape.stones.some(p=>Math.abs(x-p[0])+Math.abs(y-p[1])===1);state.cutTried=state.cutTried||touched}const color=state.turn,r=applyMove(state.board,hit.col,hit.row,color);const visual=board.playMove({...hit,color});if(!visual.ok)throw new Error('CONNECTION_MOVE_MISMATCH');state.board=r.newState;visuals();if(phase===1){state.built=completedShape(state.shape,i,x,y);el('feedback').textContent=state.shape.name+' bu yönde kuruldu. Kendi biçiminle kesme denemesine geç.';board.setInputEnabled(false);finishStep()}else{state.ply++;state.turn=color==='white'?'black':'white';el('feedback').textContent=(r.captured.length?r.captured.length+' taş alındı. ':'')+connectionStatus(state.board,state.shape).feedback+' Sıra '+(state.turn==='white'?'beyazda.':'siyahta.');if(state.cutTried&&state.ply>=2&&color==='black')finishStep()}context.emit('scene_assessment_answered',{assessmentIndex:state.step,stepIndex:state.step,concept:'connection',assessmentType:'board_tap',correct:phase===1||state.cutTried,legal:true,row:hit.row,col:hit.col})}
 el('confirm').onclick=()=>{if(state.step===0)context.emit('scene_intro_confirmed',{});finishStep()};el('reset').onclick=()=>{if(state.step%3===1){state.built=null;state.done.delete(state.step)}render()};el('next').onclick=()=>{if(!state.done.has(state.step))return;if(state.step===11){if(state.end)return;root.hidden=true;state.end=mountTopicEndControls(context,{summaryText:'Kosumi, bir aralık sıçrama, keima ve bambuyu kurdun; kesme girişimlerini ve savunmayı denedin.'});try{const saved=JSON.parse(localStorage.getItem('go_done_3d')||'[]');if(Array.isArray(saved))localStorage.setItem('go_done_3d',JSON.stringify([...new Set([...saved,'l8'])]))}catch{}const link=document.createElement('a');link.className='ls-strip-btn';link.href='ogren-3d.html?lesson=l9';link.textContent='Müfredatta devam et: Çift Atari';state.endLink=link;context.container.append(link);return}state.step++;if(state.step%3===0){state.built=null;state.direction=0}render()};render();
},
unmount(context){if(!active)return;active.alive=false;active.off?.();active.hover?.();active.end?.destroy();active.endLink?.remove();active.root.remove();context.container.classList.remove('s12-scene-host');context.boardAdapter.setInputEnabled(false);context.boardAdapter.clearMovePreview();context.boardAdapter.clearLiberties();active=null},
canComplete(){return !!active&&active.done.size===12},complete(){}
};
