import {CONNECTION_SHAPES,CONNECTION_BOARD_SIZE,CONNECTION_OFFSET,orientedShape,buildConnectionBoard,validShapeCompletion,completedShape,bambooPlacement,connectionStatus} from './connectionShapesPolicy.js?v=2026-09-16.v0-intersections1';
import {applyMove,isValidMove} from '../core/ruleEngine.js?v=2026-09-16.v0-intersections1';
import {mountTopicEndControls} from './topicEndControls.js?v=2026-09-16.v0-intersections1';
let active=null;
export const scene12Connections={
id:'scene-12-connections',version:2,title:'Kesme ve Bağlama',curriculumRef:{lessonId:'l8',concept:'connection'},
mount(context){
 const state=active={step:0,built:null,builtByTerm:new Map(),done:new Set(),alive:true,off:null,hover:null,end:null,cutTried:false};context.container.classList.add('s12-scene-host');const root=document.createElement('div');root.className='ls-strip-root s12-root';root.innerHTML='<div class="s12-heading"></div><p class="ls-strip-text s12-body"></p><nav class="s12-topics" aria-label="Bağlantı biçimleri"></nav><div class="s12-actions"><button class="ls-strip-btn s12-confirm">Anladım</button><button class="ls-strip-btn s12-reset">Yeni deneme</button><button class="ls-strip-btn s12-next" disabled>Devam</button></div><p class="s05-feedback s12-feedback" role="status"></p>';context.container.append(root);state.root=root;const el=c=>root.querySelector('.s12-'+c),board=context.boardAdapter;
 function shape(){return state.built||orientedShape(Math.floor(state.step/3),0)}
 function visuals(){board.clearMovePreview();board.clearLiberties();board.clearIllegalHints();board.clearRegionMarks()}
 function syncBoard(){board.setSize(CONNECTION_BOARD_SIZE);board.reset();visuals();for(const p of state.board.stones){const a=board.playMove({row:p.y,col:p.x,color:p.color});if(!a.ok)throw new Error('CONNECTION_SEED_MISMATCH')}board.focus('connections');board.focusPoints([...state.shape.stones.map(p=>({col:p[0]+CONNECTION_OFFSET,row:p[1]+CONNECTION_OFFSET})),{col:0,row:0},{col:8,row:8}],{presetName:'connections',minZoom:160});if(state.step%3===2)board.showLiberties(state.shape.markers.map(p=>({col:p[0]+CONNECTION_OFFSET,row:p[1]+CONNECTION_OFFSET})))}
 function finishStep(){state.done.add(state.step);el('next').disabled=false;if(state.done.size===12)context.emit('scene_completion_unlocked',{})}
 function render(){state.off?.();state.hover?.();state.shape=shape();state.board=buildConnectionBoard(state.shape,state.step%3===1);state.bambooPlaced=[state.shape.stones[0]];state.turn=state.step%3===2?'white':'black';state.cutTried=false;state.ply=0;syncBoard();const phase=state.step%3,s=state.shape;root.dataset.stepIndex=state.step;root.dataset.phase=phase;el('heading').textContent=(state.step+1)+' / 12 · '+s.name+' · '+['Tanı','Biçimi kur','Kesme ve savunmayı dene'][phase];el('body').textContent=phase===0?s.geometry+' '+s.purpose:phase===1?s.geometry+(s.name==='Bambu'?' Üç siyah taş ekleyerek bambuyu istediğin yönde kur.':' Taşını yerleştirerek yönü kendin seç.'):s.warning+' Önce beyazla kesmeyi, sonra siyahla savunmayı dene. İstediğin yasal noktalarda devam edebilirsin.';el('confirm').hidden=phase!==0;el('reset').hidden=phase===0;el('next').disabled=!state.done.has(state.step);el('feedback').textContent=phase===2?'Beyaz oynuyorsun. Bağlantı aralığını veya taşların yanını dene.':phase===1?'Siyah oynuyorsun. Biçimi boş kesişimlere taş yerleştirerek tamamla.':'';el('topics').innerHTML=CONNECTION_SHAPES.map((term,i)=>'<button class="ls-strip-btn s12-topic" data-term="'+i+'" aria-pressed="'+(i===Math.floor(state.step/3))+'" title="'+term.tr+'">'+(i===1?'Bir aralık sıçrama':term.name)+'</button>').join('');for(const btn of el('topics').querySelectorAll('[data-term]'))btn.onclick=()=>{state.step=Number(btn.dataset.term)*3;state.built=state.builtByTerm.get(Number(btn.dataset.term))||null;render()};board.setInputEnabled(phase!==0);state.off=board.onIntersectionTap(tap);state.hover=board.onIntersectionHover(hit=>{if(!hit||state.step%3===0||(state.step%3===1&&state.done.has(state.step))||!isValidMove(state.board,hit.col,hit.row,state.turn).valid)board.clearMovePreview();else board.setMovePreview({...hit,color:state.turn})});context.emit('scene_assessment_presented',{assessmentIndex:state.step,assessmentCount:12,concept:'connection',assessmentType:phase===0?'confirmation':'board_tap'})}
 function tap(hit){if(!state.alive||state.step%3===0||(state.step%3===1&&state.done.has(state.step)))return;const i=Math.floor(state.step/3),x=hit.col-CONNECTION_OFFSET,y=hit.row-CONNECTION_OFFSET,phase=state.step%3;const bamboo=phase===1&&i===3?bambooPlacement(state.shape,state.bambooPlaced,x,y):null;if(phase===1&&(i===3?!bamboo:!validShapeCompletion(state.shape,i,x,y))){el('feedback').textContent='Bu nokta biçimi tamamlamıyor. Yatay ve dikey uzaklıkları yeniden say.';return}const legal=isValidMove(state.board,hit.col,hit.row,state.turn);if(!legal.valid){el('feedback').textContent='Burada yasal hamle yok; başka boş nokta dene.';return}if(phase===2&&state.turn==='white'){const touched=state.shape.stones.some(p=>Math.abs(x-p[0])+Math.abs(y-p[1])===1);state.cutTried=state.cutTried||touched}const color=state.turn,r=applyMove(state.board,hit.col,hit.row,color);const visual=board.playMove({...hit,color});if(!visual.ok)throw new Error('CONNECTION_MOVE_MISMATCH');state.board=r.newState;visuals();if(phase===1){if(i===3){state.bambooPlaced=bamboo.stones;if(!bamboo.complete){el('feedback').textContent='Bambuyu tamamlamak için '+(4-bamboo.stones.length)+' siyah taş daha yerleştir.';return}}state.built=bamboo||completedShape(state.shape,i,x,y);state.builtByTerm.set(i,state.built);el('feedback').textContent=state.shape.name+' bu yönde kuruldu. Kendi biçiminle kesme denemesine geç.';board.setInputEnabled(false);finishStep()}else{state.ply++;state.turn=color==='white'?'black':'white';el('feedback').textContent=(r.captured.length?r.captured.length+' taş alındı. ':'')+connectionStatus(state.board,state.shape).feedback+' Sıra '+(state.turn==='white'?'beyazda.':'siyahta.');if(state.cutTried&&state.ply>=2&&color==='black')finishStep()}context.emit('scene_assessment_answered',{assessmentIndex:state.step,stepIndex:state.step,concept:'connection',assessmentType:'board_tap',correct:phase===1||state.cutTried,legal:true,row:hit.row,col:hit.col})}
 el('confirm').onclick=()=>{if(state.step===0)context.emit('scene_intro_confirmed',{});finishStep()};el('reset').onclick=()=>{if(state.step%3===1){state.built=null;state.builtByTerm.delete(Math.floor(state.step/3));state.done.delete(state.step)}render()};el('next').onclick=()=>{if(!state.done.has(state.step))return;if(state.step===11){if(state.done.size!==12){state.step=Array.from({length:12},(_,i)=>i).find(i=>!state.done.has(i));state.built=state.builtByTerm.get(Math.floor(state.step/3))||null;render();return}if(state.end)return;root.hidden=true;state.end=mountTopicEndControls(context,{summaryText:'Kosumi, bir aralık sıçrama, keima ve bambuyu kurdun; kesme girişimlerini ve savunmayı denedin.'});try{const saved=JSON.parse(localStorage.getItem('go_done_3d')||'[]');if(Array.isArray(saved))localStorage.setItem('go_done_3d',JSON.stringify([...new Set([...saved,'l8'])]))}catch{}const link=document.createElement('a');link.className='ls-strip-btn';link.href='ogren-3d.html?lesson=l10';link.textContent='Müfredatta devam et: Merdiven';state.endLink=link;context.container.append(link);return}state.step++;if(state.step%3===0){state.built=state.builtByTerm.get(Math.floor(state.step/3))||null}render()};render();
},
unmount(context){if(!active)return;active.alive=false;active.off?.();active.hover?.();active.end?.destroy();active.endLink?.remove();active.root.remove();context.container.classList.remove('s12-scene-host');context.boardAdapter.setInputEnabled(false);context.boardAdapter.clearMovePreview();context.boardAdapter.clearLiberties();active=null},
canComplete(){return !!active&&active.done.size===12},complete(){}
};
