import {BoardState} from '../core/boardState.js?v=2026-09-13.8';
import {isValidMove,applyMove,getGroup,getLiberties} from '../core/ruleEngine.js?v=2026-09-13.8';
export function seedBoard(stones){const b=new BoardState(9);for(const p of stones)b.placeStone(p.x,p.y,p.color);return b}
const pts=(color,coords)=>coords.map(([x,y])=>({x,y,color}));
const legacy=[{"seed":[{"color":"white","x":3,"y":3},{"color":"white","x":2,"y":4},{"color":"white","x":4,"y":4},{"color":"white","x":4,"y":5},{"color":"black","x":4,"y":3},{"color":"black","x":5,"y":3},{"color":"black","x":5,"y":4},{"color":"black","x":2,"y":5},{"color":"black","x":5,"y":5},{"color":"black","x":3,"y":6},{"color":"black","x":4,"y":6}],"moves":[{"x":3,"y":4,"color":"black"},{"x":3,"y":5,"color":"white"},{"x":3,"y":4,"color":"black"}]},{"seed":[{"color":"white","x":0,"y":2},{"color":"white","x":1,"y":2},{"color":"white","x":2,"y":2},{"color":"white","x":3,"y":2},{"color":"white","x":0,"y":3},{"color":"white","x":1,"y":4},{"color":"white","x":1,"y":5},{"color":"black","x":1,"y":3},{"color":"black","x":2,"y":3},{"color":"black","x":2,"y":4},{"color":"black","x":2,"y":5},{"color":"black","x":0,"y":6},{"color":"black","x":1,"y":6}],"moves":[{"x":0,"y":4,"color":"black"},{"x":0,"y":5,"color":"white"},{"x":0,"y":4,"color":"black"}]}];
// How to Play Go, PDF p.43, diagrams 7-25–27. Colours reversed for White's turn.
const central={seed:[...pts('white',[[3,2],[2,3],[2,4],[5,4],[3,5],[4,5]]),...pts('black',[[4,2],[5,3],[3,4],[4,4]])],moves:pts('white',[[4,3]])};
central.moves.push({x:3,y:3,color:'black'},{x:4,y:3,color:'white'});
// Diagram 7-29: the right-hand border is a real board edge, not a cropped interior.
const edge={seed:[...pts('black',[[7,2],[8,2],[8,3],[7,4],[7,5],[6,6],[7,6],[8,6]]),...pts('white',[[7,3],[6,3],[6,4],[6,5],[5,6],[6,7],[7,7],[8,7]])],moves:[{x:8,y:4,color:'white'},{x:8,y:5,color:'black'},{x:8,y:4,color:'white'}]};
export const SNAP_STEPS=[
 {title:'Bir taşı ver, üç taşı al',text:'Siyahla bir taş kurban et; beyazla bu taşı al; sonra siyahla boşalan noktadan üç beyaz taşı yakala. Her hamleyi kendin oyna.',form:legacy[0],kind:'snap',source:'Mevcut müfredat, ilk formasyon; devam dizisi yeniden doğrulandı.'},
 {title:'Kenarda aynı fikri oku',text:'Kenar, dışarıdan yeni nefes açılmasını önler. Kurban, beyazın alışı ve siyahın geri alışı için üç hamleyi sırayla bul.',form:legacy[1],kind:'snap',source:'Mevcut müfredat, ikinci formasyon; devam dizisi yeniden doğrulandı.'},
 {title:'Bu kez beyazla geri al',text:'Teknik renge bağlı değil. Beyazla bir taş kurban et. Siyah kurbanı aldığında grubun nefeslerini say; ardından beyazla geri al. Boşalan nokta neden yeniden oynanabilir?',form:central,kind:'snap',source:'How to Play Go, PDF s.43, 7-25–27; renkler değiştirilerek uyarlandı.'},
 {title:'Kenardaki zinciri çöz',text:'Bu farklı kenar formasyonunda beyaz oynuyorsun. Siyahın iki nefesinden birine kurban taşını yerleştir. Siyahla kurbanı al; beyazla geri alarak daha uzun zinciri yakala.',form:edge,kind:'snap',source:'How to Play Go, PDF s.43, 7-29; gerçek kenar korunarak 9×9 tahtaya taşındı; üç dış taş çıkarıldı; çevreleyen beyaz taşların bağlantısı korundu.'},
];
export function buildScenario(step){let b=seedBoard(step.form.seed);const frames=[{stones:b.stones.map(p=>({...p})),captures:[],move:null,koPoint:null}];for(const m of step.form.moves){if(!isValidMove(b,m.x,m.y,m.color).valid)throw new Error('Illegal snapback move: '+JSON.stringify(m));const r=applyMove(b,m.x,m.y,m.color);b=r.newState;frames.push({stones:b.stones.map(p=>({...p})),captures:r.captured.map(p=>({...p,color:m.color==='black'?'white':'black'})),move:m,koPoint:b.koPoint})}return {size:9,seed:step.form.seed,moves:step.form.moves,frames,board:b}}
export function groupAt(board,p){const g=getGroup(board,p.x,p.y);return {count:g.size,liberties:[...getLiberties(board,g)].map(k=>{const [x,y]=k.split(',').map(Number);return {x,y}})}}
