import assert from 'node:assert/strict';
import {orientedShape,buildConnectionBoard,validShapeCompletion,completedShape,connectionStatus} from '../scenes/connectionShapesPolicy.js';
import {scene12Connections} from '../scenes/scene12Connections.js';
import {BoardState} from '../core/boardState.js';
import {applyMove,isValidMove} from '../core/ruleEngine.js';
import {CURRICULUM} from '../core/curriculum.js';
let count=0;
for(let d=0;d<8;d++)for(let i=0;i<4;i++){const s=orientedShape(i,d),b=buildConnectionBoard(s,true);let answers=0;for(let y=0;y<6;y++)for(let x=0;x<6;x++)if(validShapeCompletion(s,i,x,y)){answers++;assert(isValidMove(b,x+6,y+6,'black').valid)}assert.equal(answers,[4,4,8,1][i]);count++}
assert.equal(CURRICULUM.flatMap(c=>c.lessons).find(l=>l.id==='l8').steps.length,12);
const saved=new Map([['go_done_3d','["l1"]']]);globalThis.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};
class Element{constructor(){this.children=new Map();this.dataset={};this.classList={add(){},remove(){}}}querySelector(k){if(!this.children.has(k))this.children.set(k,new Element());return this.children.get(k)}querySelectorAll(){return []}append(e){}appendChild(e){}remove(){}addEventListener(){}removeEventListener(){}}
globalThis.document={createElement:()=>new Element()};const container=new Element();let tap,hover,preview,visualBoard=new BoardState(19),marked=0;
const adapter={setSize(){},reset(){visualBoard=new BoardState(19)},clearMovePreview(){preview=null},clearLiberties(){},clearIllegalHints(){},clearRegionMarks(){},focusPoints(){},showLiberties(){},setInputEnabled(){},onIntersectionTap(fn){tap=fn;return ()=>{tap=null}},onIntersectionHover(fn){hover=fn;return ()=>{hover=null}},setMovePreview(p){preview=p},playMove(p){if(!isValidMove(visualBoard,p.col,p.row,p.color).valid)return {ok:false};visualBoard=applyMove(visualBoard,p.col,p.row,p.color).newState;return {ok:true}}};
let root;container.append=e=>{if(!root)root=e};scene12Connections.mount({container,boardAdapter:adapter,emit(){},markComplete(){marked++},hasNextScene:false});
for(let i=0;i<4;i++){assert.equal(scene12Connections.canComplete(),false);root.querySelector('.s12-confirm').onclick();root.querySelector('.s12-next').onclick();const s=orientedShape(i),anchor=s.stones.find(p=>p[0]!==s.root[0]||p[1]!==s.root[1]);const target=i===0?[anchor[0]-1,anchor[1]+1]:s.root;tap({col:target[0]+6,row:target[1]+6});assert.equal(root.querySelector('.s12-next').disabled,false);root.querySelector('.s12-next').onclick();assert.equal(root.querySelector('.s12-next').disabled,true);const built=completedShape(s,i,...target);const cut=built.markers[0]||[anchor[0]+1,anchor[1]];hover({col:cut[0]+6,row:cut[1]+6});assert.equal(preview.color,'white');tap({col:cut[0]+6,row:cut[1]+6});assert.equal(root.querySelector('.s12-next').disabled,true);const reply=i===0||i===3?built.markers[1]:[0,0];hover({col:reply[0]+6,row:reply[1]+6});assert.equal(preview.color,'black');tap({col:reply[0]+6,row:reply[1]+6});assert.equal(root.querySelector('.s12-next').disabled,false);if(i===0||i===3)assert.equal(connectionStatus(visualBoard,built).joined,true);root.querySelector('.s12-next').onclick()}
assert.equal(scene12Connections.canComplete(),true);assert.equal(marked,1);assert.deepEqual(JSON.parse(saved.get('go_done_3d')),['l1','l8']);scene12Connections.unmount({container,boardAdapter:adapter});assert.equal(tap,null);assert.equal(hover,null);assert.equal(scene12Connections.canComplete(),false);
console.log(count+' yön kontrolü; 12 adımlı sahne, ilerleme kapıları, beyaz/siyah önizleme, ders kaydı ve temizleme geçti.');
