import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync('go-nedir.html', 'utf8');
const css = fs.readFileSync('styles/design-system.css', 'utf8');
const count = needle => html.split(needle).length - 1;

assert.equal(count('<h1>'), 1, 'tek h1 olmal&#305;');
assert(html.includes('Go Nedir? &mdash; AntalyaGo'), 'sayfa ba&#351;l&#305;&#287;&#305; eksik');
assert(html.includes('Bir dakikada Go'), 'bir dakikada Go b&#246;l&#252;m&#252; eksik');
assert(html.includes('Oyunun amac&#305;'), 'oyunun amac&#305; b&#246;l&#252;m&#252; eksik');
assert(html.includes('&#220;&#231; temel kural'), '&#252;&#231; temel kural b&#246;l&#252;m&#252; eksik');
assert(html.includes('Nefes ve ta&#351; yakalama'), 'nefes ve yakalama b&#246;l&#252;m&#252; eksik');
assert(html.includes('Alan ve ba&#287;lant&#305;'), 'alan ve ba&#287;lant&#305; b&#246;l&#252;m&#252; eksik');
assert(html.includes('Go\'nun stratejik derinli&#287;i'), 'stratejik derinlik b&#246;l&#252;m&#252; eksik');
assert(html.includes('Neden 9&times;9?'), '9x9 b&#246;l&#252;m&#252; eksik');
assert(html.includes('9&times;9 ile ilk dersine ba&#351;la.'), 'ilk ders CTA eksik');
assert(html.includes('Az say&#305;da kural, her ta&#351;la de&#287;i&#351;en say&#305;s&#305;z olas&#305;l&#305;k.'), 'kapak caption eksik');
assert(count('class="rule-card"') === 3, '&#252;&#231; kural kart&#305; olmal&#305;');
assert(html.includes('Weiqi'), 'Weiqi korunmam&#305;&#351;');
assert(html.includes('<em>Go</em>'), 'Go ad&#305; eksik');
assert(html.includes('<em>Baduk</em>'), 'Baduk ad&#305; eksik');
assert(html.includes('4.000 y&#305;l'), '4.000 y&#305;ll&#305;k anlat&#305; eksik');
assert(html.includes('ogren-3d.html'), 'ogren-3d CTA eksik');
assert(html.includes('robot.html'), 'robot ba&#287;lant&#305;s&#305; eksik');
assert(html.includes('property="og:title"'), 'OG title eksik');
assert(html.includes('property="og:description"'), 'OG description eksik');
assert(html.includes('property="og:url"'), 'OG url eksik');
assert(html.includes('property="og:image"'), 'OG image eksik');
assert(html.includes('name="twitter:card"'), 'Twitter card eksik');
assert(html.includes('name="twitter:title"'), 'Twitter title eksik');
assert(html.includes('name="twitter:description"'), 'Twitter description eksik');
assert(html.includes('name="twitter:image"'), 'Twitter image eksik');
assert(html.includes('rel="canonical"'), 'canonical eksik');
assert(html.includes('rel="icon" type="image/svg+xml"'), 'SVG favicon eksik');
assert(html.includes('rel="icon" type="image/png" sizes="32x32"'), 'PNG favicon eksik');
assert(html.includes('rel="apple-touch-icon"'), 'apple touch icon eksik');
assert(html.includes('styles/design-system.css'), 'tasar&#305;m sistemi eksik');
assert(html.includes('styles/theme-compat.css'), 'uyumluluk CSS eksik');
assert(html.includes('core/theme.js'), 'tema beti&#287;i eksik');
assert(html.includes('data-theme-toggle'), 'tema d&#252;&#287;mesi eksik');
assert(css.includes('.editorial-page'), 'editorial-page s&#305;n&#305;f&#305; yok');
assert(css.includes('.editorial-hero'), 'editorial-hero s&#305;n&#305;f&#305; yok');
assert(css.includes('.editorial-grid'), 'editorial-grid s&#305;n&#305;f&#305; yok');
assert(css.includes('.editorial-copy'), 'editorial-copy s&#305;n&#305;f&#305; yok');
assert(css.includes('.editorial-media'), 'editorial-media s&#305;n&#305;f&#305; yok');
assert(css.includes('.prose-lead'), 'prose-lead s&#305;n&#305;f&#305; yok');
assert(css.includes('.fact-grid'), 'fact-grid s&#305;n&#305;f&#305; yok');
assert(css.includes('.rule-card'), 'rule-card s&#305;n&#305;f&#305; yok');
assert(css.includes('.callout'), 'callout s&#305;n&#305;f&#305; yok');
assert(css.includes('.quote-card'), 'quote-card s&#305;n&#305;f&#305; yok');
assert(css.includes('.inline-diagram'), 'inline-diagram s&#305;n&#305;f&#305; yok');
assert(css.includes('.chapter-nav'), 'chapter-nav s&#305;n&#305;f&#305; yok');
assert(css.includes('.closing-cta'), 'closing-cta s&#305;n&#305;f&#305; yok');
assert(css.includes('.media-caption'), 'media-caption s&#305;n&#305;f&#305; yok');

console.log('  \u2713 Go Nedir i&#231;erik/SEO testi ge&#231;ti');
